title: Ashwani Kaira Portfolio
description: A personal portfolio site hosted on GitHub Pages.
baseurl: ""  # Leave this blank if deploying at https://askaira.github.io/my-portfolio-site
url: "https://askaira.github.io"  # Your GitHub Pages domain

theme: null  # null because we are using a custom layout
plugins:
  - jekyll-seo-tag

markdown: kramdown

author:
  name: Ashwani Kaira
  email: your@email.com

social:
  github: askaira
  linkedin: your-linkedin-url
